### ISSUE TITLE
Running source <(hass-cli comletion zsh) fails

### ISSUE THREAD

**Issue by ronnyandre** [home-assistant/home-assistant-cli#141]
Tried running the `source <(hass-cli completion zsh)` returns the following error:

```
pi@hassbian:~ $ source <(hass-cli completion zsh)

-bash: /dev/fd/63: line 10: syntax error near unexpected token `descr'
-bash: /dev/fd/63: line 10: `    for key descr in ${(kv)response}; do'
```

I had to install hass-cli with sudo in order to make it install. I tried to run the source command with sudo, but that returns command not found.

**Comment by maxandersen** [comment]
Looks like you are running `bash` instead of `zsh` as shell.

Then you should use `source <(hass-cli completion bash)` instead.

On the issue with needing to run install with sudo.

If pip install did succeed but hass-cli not in your path it indicates your OS for some reason don't have the right path setup to include the destination for pip binaries installed by users.

1) What OS are you running ?
2) Did you install other pip based apps on this computer, i.e. homeassistant ? If yes, I assume it also needed to use `sudo` or ?

**Comment by ronnyandre** [comment]
Duh, I should have noticed `zsh`. I use Zsh locally, but Bash on the server. Thanks!
